database: $DATAVAULT_DATABASE_URI
table: ss_applications
nodes:
  holder:
    label: Actor
    properties:
      name:
        column: parties
      fingerprint:
        column: parties
        transform: fingerprint
        key: true
  concession:
    label: Concession
    properties:
      name:
        column: code
      description:
        column: name
      commodities:
        column: commodities
      concessionArea:
        column: area
      fingerprint:
        format: "%(source_url)s//%(code)s"
        key: true
      countryCode:
        literal: SS
  concessionLocation:
    label: Address
    properties:
      name:
        column: mapref
      fingerprint:
        column: mapref
        transform: fingerprint
        key: true
      countryCode:
        literal: SS
edges:
  - label: OWNED_BY
    source: concession
    target: holder
    properties:
      rightType:
        column: type
      legalBasis:
        column: jurisdic
      rightStatus:
        column: status
      applicationDate:
        column: dteapplied
  - label: LOCATED_AT
    source: concession
    target: concessionLocation
